//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Envanter_Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EnvanterContainer : DbContext
    {
        public EnvanterContainer()
            : base("name=EnvanterContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<KULLANICI> KULLANICISet { get; set; }
        public virtual DbSet<SUBE> SUBESet1 { get; set; }
        public virtual DbSet<URUN> URUNSet1 { get; set; }
        public virtual DbSet<SATIS> SATISSet { get; set; }
        public virtual DbSet<ALIM> ALIMSet { get; set; }
    }
}
