//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Envanter_Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class SATIS
    {
        public int SatisId { get; set; }
        public int Barkod { get; set; }
        public int Miktar { get; set; }
        public System.DateTime Date { get; set; }
        public int SubeId { get; set; }
        public int KullaniciID { get; set; }
    
        public virtual SUBE SUBE { get; set; }
    }
}
