//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Envanter_Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class URUN
    {
        public int Barkod { get; set; }
        public string UrunAdi { get; set; }
        public string UrunCinsi { get; set; }
        public string Birim { get; set; }
        public int Stok { get; set; }
        public double Birim_Fiyat { get; set; }
        public string Aciklama1 { get; set; }
        public string Aciklama2 { get; set; }
        public Nullable<int> Kritik_Stok_Seviyesi { get; set; }
        public int SubeId { get; set; }
        public int KullaniciID { get; set; }
    
        public virtual SUBE Sube { get; set; }
    }
}
